### ISSUE TITLE
no documetation on deploying a bagisto app on the live server(cpanel).

### ISSUE THREAD

**Issue by binoysarker** [bagisto/bagisto-docs#114]
i have installed bagisto version 1.0.6 using composer. and then trying to upload the project in the cpanel. I have chnged the php version to 7.1. I have also changed the app url, database details before uploding on cpanel. But it is showing error when tyring to make migration.
![image](https://user-images.githubusercontent.com/26120595/61514227-5ea49d80-aa21-11e9-9c51-3187ca2168d0.png)

How can i fix this?

**Comment by Deepanjali-Singh** [comment]
@prateek-webkul 
Is the documentation on "deploying bagisto app to live server" availabel?

**Comment by ghermans** [comment]
Bagisto can be installed with Softaculous https://www.softaculous.com/apps/ecommerce/Bagisto when using cpanel,
