### ISSUE TITLE
Adding only one language

### ISSUE THREAD

**Issue by KevinLaveto** [bagisto/bagisto-docs#132]
If you only want one language and then delete the other you get an error. I only wanted the dutch language.

![Screenshot 2019-12-02 at 14 18 55](https://user-images.githubusercontent.com/31034266/69962640-b2b2a900-150e-11ea-9fb5-17b9c3c1d6de.

This is what happened if I tried to delete the english language. (Cause you need to first add a language before you can delete the other one. Otherwise I can't edit the slug of the current language.)

**Comment by prateek-webkul** [comment]
Hi KevinLaveto,

'English' locale is bagisto default locale, so if you try to delete it will throw error. So, if you want your store in dutch language you need to create locale for dutch. And, within settings->channels , you need to set your locale.
