### ISSUE TITLE
Can't see products

### ISSUE THREAD

**Issue by KevinLaveto** [bagisto/bagisto-docs#133]
I've entered language and changed all the settings and added products and all that stuff. But after all that I can't see the products that I added.

[aromawinkel_2019-12-02.sql.zip](https://github.com/bagisto/bagisto-docs/files/3911466/aromawinkel_2019-12-02.sql.zip)

I added an sql file with my database settings, hopefully this helps. I didnt' change anything in the base files.

![Screenshot 2019-12-02 at 14 30 12](https://user-images.githubusercontent.com/31034266/69963310-446ee600-1510-11ea-829b-59c927033670.png)
![Screenshot 2019-12-02 at 14 30 06](https://user-images.githubusercontent.com/31034266/69963313-446ee600-1510-11ea-8ee1-4c2913541b26.png)

**Comment by prateek-webkul** [comment]
Hi KevinLaveto,

You need to specify the locale in config/app.php file of root as shown in screenshot, replace 'en' with your locale code.

![locale-setup](https://user-images.githubusercontent.com/48429511/70206691-5a69ea00-174e-11ea-9863-b8e8f17b29ff.png)
