### ISSUE TITLE
How to change language of error validation on front end

### ISSUE THREAD

**Issue by KevinLaveto** [bagisto/bagisto-docs#134]
![Screenshot 2019-12-10 at 16 44 48](https://user-images.githubusercontent.com/31034266/70544501-74e7fd00-1b6c-11ea-8842-53530902e411.png)
So I have a product on my 'front end' and this has error validation. Since my site needs to be dutch I want to change this. However I can't find how to change it.

I tried like searching for the error in multiple ways, tried getting the locales.js and changing the language from that.
![Screenshot 2019-12-10 at 16 47 04](https://user-images.githubusercontent.com/31034266/70544677-c4c6c400-1b6c-11ea-91ce-a0da43ac8092.png)
![Screenshot 2019-12-10 at 16 47 00](https://user-images.githubusercontent.com/31034266/70544678-c4c6c400-1b6c-11ea-8403-24acb72d08f3.png)

I have language file registrered for other translations. But even then I don't know what to put in that cause I can't find where the error is created.

*btw the double loadTranslationsFrom is a test to load my translations over the other one. But I also added my own translations in view files which start with aroma:: . So that is why there are 2, I don't know if this is like ehm 'legal'? Or something like that.

**Comment by prateek-webkul** [comment]
Hi KevinLaveto,
 
To show validation messages as per your locale, you need to follow these below steps:
 
1) Within Shop package, go to src/Resources/assets/js/lang/locales.js

2) define your error translation for your locale code as shown below in screenshot
![locale-trans](https://user-images.githubusercontent.com/48429511/70595015-2a1bc300-1c08-11ea-860d-2e44bca79c66.png)

3) Now, within app.js, add " ar: { messages: locales.messages.ar } "  for your locale code in dictionary property such as ar-for arabic 
 Vue.use(VeeValidate, {
    dictionary: {
        ar: { messages: locales.messages.ar }
    }
});

**Comment by KevinLaveto** [comment]
Thanks. Is this also in the documentation, cause I couldn't find it. If so; would be nice to add.

**Comment by prateek-webkul** [comment]
> Thanks. Is this also in the documentation, cause I couldn't find it. If so; would be nice to add.

No, right now it is not added in documentation but we will add it soon.
