### ISSUE TITLE
Second Image slider 

### ISSUE THREAD

**Issue by KevinLaveto** [bagisto/bagisto-docs#135]
I have a header with an image slider like so
![Screenshot 2019-12-11 at 15 41 56](https://user-images.githubusercontent.com/31034266/70631084-eb4c3400-1c2c-11ea-9d29-d87bb026479c.png)

This is at the top of my page. Now I would like to add a second slider (sponsors slider) at the bottom.
![Screenshot 2019-12-11 at 15 42 03](https://user-images.githubusercontent.com/31034266/70631119-f99a5000-1c2c-11ea-8ccc-7d8eb8fad722.png)

So right before my footer. 
![Screenshot 2019-12-11 at 15 43 45](https://user-images.githubusercontent.com/31034266/70631155-074fd580-1c2d-11ea-928b-fa098f29fcde.png)

Can I receive slider images from a title? So like Slider::getItemBasedOnName('sponsors').

How can I make this slider, or is there a specific place I can just upload some images. I can't upload these to my channel (since this only works on the homepage) and this slider needs to be on every page. 

I still want my client (to become admin user) to be able to edit these sponsors.

* also sorry for all these questions, bagisto works well though. So do keep up the good work.

**Comment by prateek-webkul** [comment]
Hi KevinLaveto, 

You need to create a package (refer [Package Development](https://devdocs.bagisto.com/create_package.html)) and follow below steps :  

1) You need to create menu in admin panel where you can add 'sponsor' slider data.
2) Create the table to store bottom slider data as per your requirements.
3) And, you need to listen the below event in your package.
    {!! view_render_event('bagisto.shop.layout.footer.before') !!}
4)  Within your blade render the slider for footer.

**Comment by prateek-webkul** [comment]
Hi KevinLaveto, 

You may raise the issue on [Bagisto](https://github.com/bagisto/bagisto) or post your questions on [Bagisto Forum](https://forums.bagisto.com/). Here, you may post your queries related to bagisto documentation as this is documentation Repository.

Thanks

**Comment by KevinLaveto** [comment]
Well I asked here cause I wanted this to be in the documentation as well. But i'll ask on bagisto forum i've i have more questions. 

Thanks for the help

**Comment by prateek-webkul** [comment]
> Well I asked here cause I wanted this to be in the documentation as well. But i'll ask on bagisto forum i've i have more questions.
> 
> Thanks for the help

Ok. We will add this topics in documentation.

Thanks
