### ISSUE TITLE
How to change product image upload URL?

### ISSUE THREAD

**Issue by testforpostman7** [bagisto/bagisto-docs#143]
Hello,
  
   I changed the product image storage path to storage/product directory But when getting that image on the front side It is not displayed on the home page. It will display a default placeholder image instead of the uploaded image. So how to get a product image with different size.

Thanks.

**Comment by prateek-webkul** [comment]
HI testforpostman7 ,

You may refer to below link for the product image issue.

https://forums.bagisto.com/topic/188/broken-image-logo-in-bagisto-with-causes-and-solutions

Read [File Storage in laravel](https://laravel.com/docs/5.8/filesystem#the-public-disk) for more information.

Thanks

**Comment by testforpostman7** [comment]
Hello prateek-webkul,

  This solution is helps me to resolve my issue.

Thanks.
