### ISSUE TITLE
Pass another value in place of id in cms edit api

### ISSUE THREAD

**Issue by testforpostman7** [bagisto/bagisto-docs#150]
Hello,

   I have to pass another value in place of id in admin/cms/update API in CMS module. So where I can change code to pass another value in place of id. Please give me a reply as soon as possible.

Thanks.

**Comment by prateek-webkul** [comment]
Hello testforpostman7,

You need to follow below steps:

1) You need to override PageController of CMS package located in 
 "packages/Webkul/CMS/src/Http/Controllers/Admin/PageController.php".
2) Within update method of your overrided controller, you need to pass respective parameter you need in place of 'id'.

Thanks

**Comment by testforpostman7** [comment]
Hello prateek-webkul,
  
   First I need to pass my hash id on edit page to fill CMS data based on that hash id. But I am not able to pass data on that page. So please give me a solution for how to pass my hash id value on edit page in place of id value.

Thanks

**Comment by prateek-webkul** [comment]
@testforpostman7 

You need to override routes of admin pakage in your package to call your controller method. Refer [override route](https://forums.bagisto.com/topic/320/how-to-override-your-webkul-controllers-repository-and-classes/2)

**Comment by testforpostman7** [comment]
@prateek-webkul

  I am passing my hash id value from packages/Webkul/Ui/src/Resources/views/datagrid/body.blade.php file from where id passed on edit page. But I am passing hash_id value in place of id it give me error. So How can I pass this value from body.blade.php file.

Thanks.

**Comment by prateek-webkul** [comment]
@testforpostman7 

Please attach screenshot of your error, and where you are passing hash_id in code

**Comment by testforpostman7** [comment]
@prateek-webkul 
  
   I am passing hash_id to body.blade.php using the below steps.

1. Add hash_id field in cms_pages table.
2. Add protected $index1 = 'hash_id';
3. Add hash_id field in queryBuilder
4. Change in UI->DataGrid->DataGrid.php File
   protected $index1 = null; and then pass that value into render function('index1' => $this->index1)
5. Same changes as point 4 as in table.blade.php file.
  
 When Pass index1 value in body.blade.php It gives an error.

![Screenshot from 2020-03-06 15-58-17](https://user-images.githubusercontent.com/61349669/76076325-a84bf380-5fc4-11ea-948f-b97141865c83.png)

 Thanks.

**Comment by prateek-webkul** [comment]
@testforpostman7,

You need to override the edit.blade.php located in "packages/Webkul/Admin/src/Resources/views/cms/edit.blade.php" for editing cms pages and then follow steps told above of overriding controller and route. There is no need of any changes in UI package.

Thanks

**Comment by testforpostman7** [comment]
@prateek-webkul 

   When We are changing in body.blade.php file at that time it gives us an error on the listing page. So we are not redirecting on edit.blade.php file.

Thanks.

**Comment by prateek-webkul** [comment]
@testforpostman7,

- You don't have to change any thing in UI package. Only you need to override index.blade.php file in packages/Webkul/Admin/src/Resources/views/cms/index.blade.php

- pass your grid in overrided index.blade.php file in place of CMSPageDataGrid of admin package

Within your datagrid, you may define the route for edit.(Refer https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Admin/src/DataGrids/CMSPageDataGrid.php#L58)

Thanks

**Comment by testforpostman7** [comment]
@prateek-webkul

  Please provide me any solution regarding this issue.

Thanks.

**Comment by prateek-webkul** [comment]
Hello testforpostman7,

You don't have to do any changes in UI package, you need to follow steps:

- Override index.php file from packages/Webkul/Admin/src/Resources/views/cms/index.blade.php in your package. Refer [Override View](https://forums.bagisto.com/topic/221/how-to-override-view-file-in-bagisto)
- Make you own CMS data grid and pass it in your overrided index.blade.php file 
- Within edit action pass your overrided route as told above, and within your datagrid
replace  protected $index = 'id'; with protected $index = 'hash_id';

**Comment by prateek-webkul** [comment]
Hello @testforpostman7,

This issue has been opened for 10 days. And, it seems that your issue is resolved. Therefore, I am closing the issue.

Thanks
