### ISSUE TITLE
How to pass value in datagrid

### ISSUE THREAD

**Issue by testforpostman7** [bagisto/bagisto-docs#151]
Hello,

  I have to pass the value on the Datagrid file from the index.blade.php file. So how can I pass a value to the Datagrid file? Please give me a reply.

Thanks,

**Comment by prateek-webkul** [comment]
Hello testforpostman7,

Refer https://forums.bagisto.com/topic/1278/pass-parameter-to-datagrid/2 for solution.

Thanks

**Comment by testforpostman7** [comment]
Hello prateek-webkul,

 Above This solution solved my issue.

Thanks.
