### ISSUE TITLE
Vue component changes not working

### ISSUE THREAD

**Issue by testforpostman7** [bagisto/bagisto-docs#153]
Hello,

   When I made changes in vue component to alert hello message but it is not working. So How can I get vue component changes?

Please give me a reply as soon as possible.

Thanks.

**Comment by shubhwebkul** [comment]
Hi @testforpostman7 
You need to run command - npm run watch at the package directory and clear browser's cache then check.

If you're still facing issue, please share in which package you're making changes.

thanks!

**Comment by testforpostman7** [comment]
Hello @shubhwebkul 

When We run the npm run watch command we got below error.

sh: 1: cross-env: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ankit/.npm/_logs/2020-03-24T06_12_22_668Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ watch: `npm run development -- --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

Please give me a reply.

Thanks.

**Comment by prateek-webkul** [comment]
@testforpostman7 , please run "npm install" before "npm run watch" command.

**Comment by prateek-webkul** [comment]
Hey @testforpostman7 ,

This issue has been opened for more than 10 days. And, it seems that your issue is resolved. Therefore, I am closing the issue.

Thanks
