### ISSUE TITLE
How to add new icon in bagisto admin panel?

### ISSUE THREAD

**Issue by testforpostman7** [bagisto/bagisto-docs#154]
Hello,

  How to add a new icon in bagisto admin panel. Please guide me on how to add a new icon.

Thanks..

**Comment by prateek-webkul** [comment]
Hi @testforpostman7 ,

You may raise the issue on [Bagisto](https://github.com/bagisto/bagisto) or post your questions on [Bagisto Forum](https://forums.bagisto.com/). Here, you may post your queries related to bagisto documentation as this is documentation Repository.

Thanks

**Comment by prateek-webkul** [comment]
Hi @testforpostman7,
 
As issue has been raised on bagisto repository. So, I am closing this issue now. Refer https://github.com/bagisto/bagisto/issues/2774 for more details about your issue. 

Thanks

**Comment by vemulaharshith** [comment]
I want to download a new icon from internet which is not avilable on bagisto and want to use it on bagisto.In admin panel and in shop both.How to do it ?

**Comment by tashitshewang123** [comment]
How to download a new icons and replace it for admin panel?
