### ISSUE TITLE
package create documentation issue

### ISSUE THREAD

**Issue by webkulabhi** [bagisto/bagisto-docs#165]
need to updated following
1 => https://prnt.sc/sgmyja
2 => https://prnt.sc/sgnd4g
3 => https://prnt.sc/sgnevu
4 => https://prnt.sc/sgnji4
5 =>https://prnt.sc/sgnm47
6 => https://prnt.sc/sgns6x
7 => https://prnt.sc/sgnx2i
8 => https://prnt.sc/sgorr8
9 => https://prnt.sc/sgp3ts
10 => https://prnt.sc/sgpb74
11 =>https://prnt.sc/sgpcsr
12 => https://prnt.sc/sgpk99
13 => https://prnt.sc/sgpuxf
14 => https://prnt.sc/sgpyae
i will check more ..

**Comment by prateek-webkul** [comment]
Hello @webkulabhi ,

Thanks for reporting the issue. We have done the respective changes as attached in issue. You may find the changes as soon as PR gets merged.

Thanks
