### ISSUE TITLE
Can we send token in headers to access API

### ISSUE THREAD

**Issue by haratmalli** [bagisto/bagisto-docs#180]

**Comment by shivam-webkul** [comment]
Yes you can send the token into the header.

**Comment by haratmalli** [comment]
how???
Any example.

**Comment by shivam-webkul** [comment]
ref link https://github.com/bagisto/bagisto/issues/3080

please follow the given link

**Comment by haratmalli** [comment]
> how???
> Any example.

Means there is no option available in backend to verify token coming along with headers and response back requested data. Only unauthorized return because this is not handled

**Comment by ghermans** [comment]
Sorry for the late response, we are planning to improve the docs related to api authentication #214.

**Comment by Sushantstha** [comment]
Still I getting unauthorized response even we send bearer token.

**Comment by haratmalli** [comment]
> Still I getting unauthorized response even we send bearer token.

try to send token as a query parameter ex. api_url?token={token}, in order to authorize access

**Comment by Sushantstha** [comment]
public/api/customer/login?token=true did the same thing

> > Still I getting unauthorized response even we send bearer token.
> 
> try to send token as a query parameter ex. api_url?token={token}, in order to authorize access

**Comment by haratmalli** [comment]
> public/api/customer/login?token=true did the same thing
> 
> > > Still I getting unauthorized response even we send bearer token.
> > 
> > 
> > try to send token as a query parameter ex. api_url?token={token}, in order to authorize access

after login you need to send login along with your api request to protected routes

**Comment by Sushantstha** [comment]
> > public/api/customer/login?token=true did the same thing
> > > > Still I getting unauthorized response even we send bearer token.
> > > 
> > > 
> > > try to send token as a query parameter ex. api_url?token={token}, in order to authorize access
> 
> after login you need to send token along with your api request to protected routes

I am sending bearer string-token. Still getting unauthenticated.
