### ISSUE TITLE
include dependencies for a package

### ISSUE THREAD

**Issue by iateadonut** [bagisto/bagisto-docs#181]
I'm creating a package that has a dependency.

Where do I put it and how do I handle it so that it is included in bagisto when doing 'composer install/update'?

my composer.json within my package would simply look like this:

{
    "require": {
        "maatwebsite/excel": "^3.1"
    }
}

**Comment by prateek-webkul** [comment]
Hey @iateadonut ,

The dependency "maatwebsite/excel": "^3.1" is already available in bagisto project. If you want to add dependency then it must be added in root composer.json file of project

Thanks

**Comment by prateek-webkul** [comment]
Hey @iateadonut ,

Hope your query has been resolved, we are closing the issue. If still you have some doubts or issues, feel free to open the issue...

Thanks
