### ISSUE TITLE
Missing docs for image search

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto-docs#220]
Documentation is required when using the image search feature (Tensorflow) with a new theme.

**Comment by devansh-webkul** [comment]
Hi @ghermans,

I have checked the source codes. Image search is already coming with the Shop package and no code is required to run the image search.

It already depends on the development, user can already take a reference from the Shop and Velocity package as well.

**Comment by devansh-webkul** [comment]
Hi @ghermans,

I am just giving the basic sample for adding the image search. Trying my best to suggest that.
