### ISSUE TITLE
Replace api docs with swagger

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto-docs#284]
As discussed earlier we are going to migrate the api docs to swagger

**Comment by dannykopping** [comment]
Has there been any progress made on this? I'm seeing some errors in the API documentation, and an OpenAPI spec would be far easier to use.

**Comment by ghermans** [comment]
Hi @dannykopping, unfortunately we have not started to work on this yet.
The focus is currently on completing the new bagisto version and when we are done with this we will update the documentation site.

**Comment by dannykopping** [comment]
OK great. Thanks for the awesome product :heart:
