### ISSUE TITLE
package create documentation missing steps

### ISSUE THREAD

**Issue by derMart** [bagisto/bagisto-docs#286]
I followed the bagisto package generator style docs to create a bagisto package: https://devdocs.bagisto.com/1.x/packages/create-package.html#_1-by-using-bagisto-package-generator
But after reloading the admin url, the created package still was missing.
I had to do some additional steps as follows:
1. run `npm install` inside the package directory to get all node.js dependencies
2. run `npm run dev` to compile all css / js and merge all css into the laravell app (otherwise no package icon was visible inside the admin url)
3. run `php artisan optimize` to get the package shown at all

It would be nice if you could update the docs.

**Comment by prateek-webkul** [comment]
Hello @derMart, 

We have updated the required changes. You may take pull from master after [PR #308](https://github.com/bagisto/bagisto-docs/pull/308) gets merged.

Thanks
