### ISSUE TITLE
Add missing docs for ui kit

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto-docs#296]
Currently the docs do not contain any information regarding the UI kit components (buttons, input, checkboxes etc..)

**Comment by amit-webkul** [comment]
Hello @ghermans ,

In the new update to the rest of the API, the UI kit is removed. We added a theme section instead of a UI kit. You can check out the theme section from [here](https://devdocs.bagisto.com/1.5.x/themes/#themes).
