### ISSUE TITLE
captcha not working on bagisto setup which is provided by bagisto.

### ISSUE THREAD

**Issue by akies1** [bagisto/bagisto-docs#348]
anchor:1 Uncaught (in promise) Timeout (f)

setTimeout (async) |   |  
-- | -- | --
  | T.<computed> | @ | recaptcha__en.js:156
  | (anonymous) | @ | recaptcha__en.js:62
  | (anonymous) | @ | recaptcha__en.js:725
  | (anonymous) | @ | recaptcha__en.js:233
  | F.<computed>.F.<computed>.next | @ | recaptcha__en.js:420
  | (anonymous) | @ | recaptcha__en.js:370
  | (anonymous) | @ | recaptcha__en.js:370
  | (anonymous) | @ | recaptcha__en.js:49
  | l9.send | @ | recaptcha__en.js:725
  | (anonymous) | @ | recaptcha__en.js:138
  | (anonymous) | @ | recaptcha__en.js:92
  | (anonymous) | @ | recaptcha__en.js:233
  | F.<computed>.F.<computed>.throw | @ | recaptcha__en.js:420
  | Z | @ | recaptcha__en.js:370
  | Promise.then (async) |   |  
  | S | @ | recaptcha__en.js:370
  | (anonymous) | @ | recaptcha__en.js:370
  | (anonymous) | @ | recaptcha__en.js:370
  | (anonymous) | @ | recaptcha__en.js:49
  | (anonymous) | @ | recaptcha__en.js:90
  | (anonymous) | @ | recaptcha__en.js:234
  | (anonymous) | @ | recaptcha__en.js:233
  | F.<computed>.F.<computed>.next | @ | recaptcha__en.js:420
  | (anonymous) | @ | recaptcha__en.js:370
  | (anonymous) | @ | recaptcha__en.js:370
  | (anonymous) | @ | recaptcha__en.js:49
  | (anonymous) | @ | recaptcha__en.js:234
  | (anonymous) | @ | recaptcha__en.js:754
  | (anonymous) | @ | anchor?ar=1&k=6LeIxA…cb=t7lsloh4p6pj:183

**Comment by akies1** [comment]
This issue is still there.

**Comment by devansh-webkul** [comment]
Please provide the steps and configuration that you have used. So that we can check and reopen the issue.
