### ISSUE TITLE
Installation fails with sql error

### ISSUE THREAD

**Issue by helgator** [bagisto/bagisto-docs#350]
Using the GUI web installer or the CLI leads to:
`
Column not found: 1054 Unknown column 'products.type' in '  field list' (Connection: mysql, SQL: update `bagis_product_flat` inner join   `bagis_products` on `bagis_product_flat`.`product_id` = `bagis_products`.`  id` set `bagis_product_flat`.`type` = products.type, `bagis_product_flat`.`  attribute_family_id` = products.attribute_family_id)In Connection.php line 599:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'products.type' in '  field list'`

**Comment by ghermans** [comment]
Please report bugs related to Bagisto on the correct repository https://github.com/bagisto/bagisto/issues

**Comment by amit-webkul** [comment]
This issue is not related to Bagisto Docs, so I am closing this issue.
