### ISSUE TITLE
Bug with `php artisan scout:import` on Bagisto v1.5.1 and Elasticsearch 7.17.13

### ISSUE THREAD

**Issue by Plansol** [bagisto/bagisto-docs#356]
I'm encountering an issue when trying to reindex products on Bagisto v1.5.1 using Elasticsearch 7.17.13, following the guide provided in the [BagistoDevDocs](https://devdocs.bagisto.com/1.x/advanced/indexing-products-to-elasticsearch.html#indexing)

When I run the following command:

`php artisan scout:import Webkul\Product\Models\ProductFlat`
I'm getting the following error message:

```
In ForwardsCalls.php line 71:
Call to undefined method Webkul\Product\Models\ProductFlat::makeAllSearchable()
```
It seems like there is an issue with the makeAllSearchable() method.

Could you please provide guidance on which command I should use to reindex my products correctly?

Thank you for your assistance.

**Comment by amit-webkul** [comment]
Hello @Plansol ,
If you want to reindex all your products in Elastic, you need to run the command given below:

> php artisan indexer:index

Also, you can follow the latest [user guide](https://devdocs.bagisto.com/1.5.x/advanced/indexing-products-to-elasticsearch.html#indexing).
